---
- name: check if postgresql repo is installed
  command: rpm -qa pgdg-centos11
  args:
    warn: False
  register: postgresql_repo_installed

- name: install postgresql repo
  yum:
    name: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when: postgresql_repo_installed.stdout == ""
